theme: jekyll-theme-minimal
title: Confomeety Boards and Meeting Agenda Management
description: Confomeety is an application that allows companies, organizations and governments to manage their meeting agenda. 
